global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: flink
    static_configs:
      - targets: ['flink-jobmanager:8081']
    metrics_path: /

  - job_name: redpanda
    static_configs:
      - targets: ['redpanda:9644']

  - job_name: postgres
    static_configs:
      - targets: ['postgres:5432']